modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Mineral%20Chance"
logoFile="icon.png"

[[mods]]
modId="mineralchance"
version="3.7"
displayName="Mineral Chance"
displayURL="https://serilum.com/mod/mineral-chance"
authors="Rick South"
description='''Adds a chance to find a random mineral inside a stone block when mining.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.mineralchance]]
    modId="collective"
    mandatory=true
    versionRange="[7.88,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mineralchance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"
